title: Masi Unnisa
name: Mona
user_description: Commonplace Book powered by Obsidian and Jekyll
notes_url: "https://masiunnisa.netlify.app"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: MIT
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://masiunnisa.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8
exclude: ["_notes/bin/*"]
# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-toc

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: null
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge


sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

toc:
  max_level: 3

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
